version: '3'
services:
  dev:
   container_name: decision
   build:
     context: .
     dockerfile: Dockerfile
   command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
   ports:
     - "3000:3000"
   volumes:
     - ../decision-matrix:/myapp
   depends_on:
     - postgres-decision

  web:
    container_name: decision-web
    build:
      context: vuejs
      dockerfile: Dockerfile
    command: npm run dev
    ports:
        - "8080:8080"
    volumes:
      - ./vuejs:/code

  server:
    container_name: go-echo-dm
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "8000:8000"

  postgres-decision:
    container_name: postgres-decision
    image: postgres:9.6

