FROM ruby:2.2.2

RUN apt-get update -qq && apt-get install -y build-essential

# for postgres
RUN apt-get install -y libpq-dev
# for nokogiri
RUN apt-get install -y libxml2-dev libxslt1-dev
# for a JS runtime
RUN apt-get install -y nodejs
RUN apt-get install -y vim

ENV APP_HOME /myapp
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

USER root

COPY . /myapp/

RUN cd /myapp/
RUN bundle install
RUN rails assets:precompile
